/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.viewsoperations;

import com.mycompany.interfaces.DAOStudents;
import com.mycompany.models.Students;
import com.mycompany.robotekpproject.DAOStudentsImpl;
import com.mycompany.views.*;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author David Fregozo
 */
public class JPanelAddStudent extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public JPanelAddStudent() {
        initComponents();
        InitStyles();
    }
    
    public void InitStyles() {
        buttons.add(rbtnTrue);
        buttons.add(rbtnFalse);
        rbtnTrue.setSelected(true);
        
        JLabel[] labels = {lbl1,lbl2,lbl3,lbl4,lbl5,lbl6,lbl7,lbl8,lbl9,lbl10,lbl11,lbl12,lbl13,lbl14,lbl15,lbl16,lbl17};
        JTextField[] txtFields = {txtNoControl,txtName,txtAge, txtTypeBlood, txtGradeLevel, txtTutor, txtPhoneNumber, txtEmail, txtEmergencyContact, txtEmergencyPhoneNumber, txtStreet, txtNo, txtApt, txtDistrict, txtCity};
        
        lblTitle.putClientProperty( "FlatLaf.style", "font: $h2.regular.font" );
        lblTitle.setForeground(Color.black);
        
        txtAllergyDescription.putClientProperty( "FlatLaf.style", "font: 13 $h3.regular.font");
        txtAllergyDescription.setBackground(Color.white);
        txtAllergyDescription.setForeground(Color.black);
        
        btnAddStudent.putClientProperty( "FlatLaf.style", "font: 14 $h3.regular.font" );
        btnAddStudent.setForeground(Color.white);
        
        Color colorGris=new Color(153, 153, 153);   
        
        for (int x=0; x<txtFields.length; x++) {
            txtFields[x].putClientProperty( "FlatLaf.style", "font: 13 $h3.regular.font" );
            txtFields[x].setForeground(colorGris);
            txtFields[x].setBackground(Color.white);
        }
        
        for (int x=0; x<labels.length; x++) {
            labels[x].putClientProperty( "FlatLaf.style", "font: 13 $light.font" );
            labels[x].setForeground(Color.black);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttons = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        bg = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtNoControl = new javax.swing.JTextField();
        lbl17 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lbl7 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        txtTutor = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        lbl8 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        txtTypeBlood = new javax.swing.JTextField();
        rbtnTrue = new javax.swing.JRadioButton();
        txtGradeLevel = new javax.swing.JTextField();
        rbtnFalse = new javax.swing.JRadioButton();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        txtAllergyDescription = new javax.swing.JTextField();
        lbl6 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        lbl9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbl10 = new javax.swing.JLabel();
        txtEmergencyContact = new javax.swing.JTextField();
        txtEmergencyPhoneNumber = new javax.swing.JTextField();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        lbl13 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        txtApt = new javax.swing.JTextField();
        lbl14 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        txtDistrict = new javax.swing.JTextField();
        lbl16 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        btnAddStudent = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(744, 487));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(744, 487));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(744, 730));

        lblTitle.setText("AGREGAR NUEVO ALUMNO");

        lbl1.setText("Nombre");

        txtName.setText("Ingresa el nombre del alumno:");
        txtName.setBorder(null);
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNameMousePressed(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtNoControl.setText("Ingresa el numero de control del alumno:");
        txtNoControl.setBorder(null);
        txtNoControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNoControlMousePressed(evt);
            }
        });
        txtNoControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoControlActionPerformed(evt);
            }
        });

        lbl17.setText("Numero de control ");

        lbl7.setText("Tutor");

        txtAge.setText("Ingresa la edad del alumno:");
        txtAge.setBorder(null);
        txtAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAgeMousePressed(evt);
            }
        });

        lbl2.setText("Edad");

        txtTutor.setText("Ingresa el nombre del tutor:");
        txtTutor.setBorder(null);
        txtTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTutorMousePressed(evt);
            }
        });
        txtTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTutorActionPerformed(evt);
            }
        });

        txtPhoneNumber.setText("Ingresa el numero de telefono del tutor:");
        txtPhoneNumber.setBorder(null);
        txtPhoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPhoneNumberMousePressed(evt);
            }
        });
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        lbl8.setText("Telefono");

        lbl3.setText("Tipo de sangre");

        txtTypeBlood.setText("Ingresa el tipo de sangre del alumno:");
        txtTypeBlood.setBorder(null);
        txtTypeBlood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTypeBloodMousePressed(evt);
            }
        });

        rbtnTrue.setText("SI");
        rbtnTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTrueActionPerformed(evt);
            }
        });

        txtGradeLevel.setText("Ingresa el grado escolar del alumno:");
        txtGradeLevel.setBorder(null);
        txtGradeLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtGradeLevelMousePressed(evt);
            }
        });

        rbtnFalse.setText("NO");
        rbtnFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFalseActionPerformed(evt);
            }
        });

        lbl4.setText("Grado escolar");

        lbl5.setText("Alergias");

        txtAllergyDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergyDescriptionActionPerformed(evt);
            }
        });

        lbl6.setText("Descripcion de alergias");

        lbl9.setText("Correo");

        txtEmail.setText("Ingresa el correo electronico del tutor:");
        txtEmail.setBorder(null);
        txtEmail.setPreferredSize(new java.awt.Dimension(288, 16));
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEmailMousePressed(evt);
            }
        });

        lbl10.setText("Contacto de emergencia");

        txtEmergencyContact.setText("Ingresa el nombre del contacto de emergencia:");
        txtEmergencyContact.setBorder(null);
        txtEmergencyContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEmergencyContactMousePressed(evt);
            }
        });
        txtEmergencyContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmergencyContactActionPerformed(evt);
            }
        });

        txtEmergencyPhoneNumber.setText("Ingresa el telefono del contacto de emergencia:");
        txtEmergencyPhoneNumber.setBorder(null);
        txtEmergencyPhoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEmergencyPhoneNumberMousePressed(evt);
            }
        });

        lbl11.setText("Telefono del contacto de emergencia");

        lbl12.setText("Domicilio-Calle");

        txtStreet.setText("Ingresa el domicilio del alumno:");
        txtStreet.setBorder(null);
        txtStreet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtStreetMousePressed(evt);
            }
        });
        txtStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetActionPerformed(evt);
            }
        });

        lbl13.setText("Num. Exterior");

        txtNo.setText("Num.Ext");
        txtNo.setBorder(null);
        txtNo.setPreferredSize(new java.awt.Dimension(133, 16));
        txtNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNoMousePressed(evt);
            }
        });

        txtApt.setText("Num.Int");
        txtApt.setBorder(null);
        txtApt.setPreferredSize(new java.awt.Dimension(133, 16));
        txtApt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAptMousePressed(evt);
            }
        });

        lbl14.setText("Num. Interior");

        lbl15.setText("Colonia");

        txtDistrict.setText("Ingrese la colonia:");
        txtDistrict.setBorder(null);
        txtDistrict.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDistrictMousePressed(evt);
            }
        });
        txtDistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistrictActionPerformed(evt);
            }
        });

        lbl16.setText("Ciudad");

        txtCity.setText("Ingrese la ciudad:");
        txtCity.setBorder(null);
        txtCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCityMousePressed(evt);
            }
        });

        btnAddStudent.setBackground(new java.awt.Color(1, 167, 91));
        btnAddStudent.setText("AGREGAR");
        btnAddStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddStudentMouseClicked(evt);
            }
        });
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(184, 184, 184))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(184, 184, 184))
                    .addComponent(jSeparator16)
                    .addComponent(txtNoControl)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(166, 166, 166))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnTrue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnFalse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(148, 148, 148))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(215, 215, 215))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(209, 209, 209))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(262, 262, 262))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(260, 260, 260))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(241, 241, 241))
                    .addComponent(jSeparator7)
                    .addComponent(txtPhoneNumber)
                    .addComponent(jSeparator6)
                    .addComponent(txtTutor)
                    .addComponent(jSeparator5)
                    .addComponent(txtAllergyDescription)
                    .addComponent(jSeparator4)
                    .addComponent(txtGradeLevel)
                    .addComponent(jSeparator3)
                    .addComponent(txtTypeBlood)
                    .addComponent(jSeparator2)
                    .addComponent(txtAge)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addComponent(jSeparator1))
                .addGap(59, 59, 59)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(158, 158, 158))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(90, 90, 90))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(208, 208, 208))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(248, 248, 248))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(250, 250, 250))
                    .addComponent(jSeparator11)
                    .addComponent(txtStreet)
                    .addComponent(jSeparator10)
                    .addComponent(txtEmergencyPhoneNumber)
                    .addComponent(jSeparator9)
                    .addComponent(txtEmergencyContact)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDistrict, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(lbl13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(58, 58, 58))
                                    .addComponent(jSeparator12)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(txtNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1)))
                                .addGap(12, 12, 12)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lbl14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(50, 50, 50))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(txtApt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(3, 3, 3))
                                    .addComponent(jSeparator15))))
                        .addGap(2, 2, 2))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(252, 252, 252))
                    .addComponent(jSeparator8)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl9, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                        .addGap(13, 13, 13)))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNoControl, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl10, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmergencyContact, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator16)
                        .addGap(4, 4, 4)
                        .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTypeBlood, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGradeLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbtnTrue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnFalse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAllergyDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(lbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTutor, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(lbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(lbl11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmergencyPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 7, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(lbl12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStreet, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                            .addComponent(jSeparator15, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDistrict, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                        .addGap(23, 23, 23)
                        .addComponent(btnAddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jScrollPane1.setViewportView(bg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNoControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoControlActionPerformed

    private void txtTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTutorActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void rbtnFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFalseActionPerformed
        txtAllergyDescription.setEnabled(false);
    }//GEN-LAST:event_rbtnFalseActionPerformed

    private void txtEmergencyContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmergencyContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmergencyContactActionPerformed

    private void txtStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetActionPerformed

    private void txtDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistrictActionPerformed

    private void btnAddStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddStudentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddStudentMouseClicked

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        int age = 0;
        Students st = new Students();
        String name = txtName.getText();
        String noControl = txtNoControl.getText();
        String textAge = txtAge.getText();
        String bloodType = txtTypeBlood.getText();
        String gradeLevel = txtGradeLevel.getText();
        boolean allergys = true;
        if (rbtnFalse.isSelected()) {
            allergys = true;
        }
        String AllergyDescription = txtAllergyDescription.getText();
        String tutorName = txtTutor.getText();
        String tutorPhoneNumber = txtPhoneNumber.getText();
        String email = txtEmail.getText();
        String emergencyContact = txtEmergencyContact.getText();
        String emergencyPhoneNumber = txtEmergencyPhoneNumber.getText();
        String street = txtStreet.getText();
        String exteriorNumber = txtNo.getText();
        String interiorNumber = txtApt.getText();
        String neighborhood = txtDistrict.getText();
        String city = txtCity.getText();
        
        if (txtName.getText().equals("Ingresa el nombre del alumno:") ||
            txtNoControl.getText().equals("Ingresa el numero de control del alumno:") ||
            txtAge.getText().equals("Ingresa la edad del alumno:") ||
            txtTypeBlood.getText().equals("Ingresa el tipo de sangre del alumno:") ||
            txtGradeLevel.getText().equals("Ingresa el grado escolar del alumno:") ||
            txtTutor.getText().equals("Ingresa el nombre del tutor:") ||
            txtPhoneNumber.getText().equals("Ingresa el numero de telefono del tutor:") ||
            txtEmail.getText().equals("Ingresa el correo electronico del tutor:") ||
            txtEmergencyContact.getText().equals("Ingresa el nombre del contacto de emergencia:") ||
            txtEmergencyPhoneNumber.getText().equals("Ingresa el telefono del contacto de emergencia:") ||
            txtStreet.getText().equals("Ingresa el domicilio del alumno:") ||
            txtNo.getText().equals("Num.Ext") ||
            txtApt.getText().equals("Num.Int") ||
            txtDistrict.getText().equals("Ingrese la colonia:") ||
            txtCity.getText().equals("Ingrese la ciudad:")) {
                JOptionPane.showMessageDialog(this, "Debe llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (name.isEmpty() || noControl.isEmpty() || textAge.isEmpty() || bloodType.isEmpty() ||
            gradeLevel.isEmpty() || tutorName.isEmpty() ||
            tutorPhoneNumber.isEmpty() || email.isEmpty() || emergencyContact.isEmpty() ||
            emergencyPhoneNumber.isEmpty() || street.isEmpty() || exteriorNumber.isEmpty() ||
            interiorNumber.isEmpty() || neighborhood.isEmpty() || city.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                try {
                    age = Integer.parseInt(textAge);
                    st.setAge(age);
                    st.setNoControl(noControl);
                    st.setStudentName(name);
                    st.setBloodType(bloodType);
                    st.setGradeLevel(gradeLevel);
                    st.setAllergies(allergys);
                    st.setAllergyDescription(AllergyDescription);
                    st.setTutorName(tutorName);
                    st.setTutorPhoneNumber(tutorPhoneNumber);
                    st.setEmail(email);
                    st.setEmergencyContact(emergencyContact);
                    st.setEmergencyPhoneNumber(emergencyPhoneNumber);
                    st.setStreet(street);
                    st.setExteriorNumber(exteriorNumber);
                    st.setInteriorNumber(interiorNumber);
                    st.setNeighborhood(neighborhood);
                    st.setCity(city);


                    try {
                        DAOStudents dao = new DAOStudentsImpl();
                        dao.enroll(st);
                        JOptionPane.showMessageDialog(this, "ALUMNO INGRESADO CON EXITO", "INGRESO", JOptionPane.INFORMATION_MESSAGE);
                        txtName.setForeground(new Color(153, 153, 153));
                        txtName.setText("Ingresa el nombre del alumno:");

                        txtNoControl.setForeground(new Color(153, 153, 153));
                        txtNoControl.setText("Ingresa el numero de control del alumno:");

                        txtAge.setForeground(new Color(153, 153, 153));
                        txtAge.setText("Ingresa la edad del alumno:");

                        txtTypeBlood.setForeground(new Color(153, 153, 153));
                        txtTypeBlood.setText("Ingresa el tipo de sangre del alumno:");
                        
                        txtGradeLevel.setForeground(new Color(153, 153, 153));
                        txtGradeLevel.setText("Ingresa el grado escolar del alumno:");

                        txtTutor.setForeground(new Color(153, 153, 153));
                        txtTutor.setText("Ingresa el nombre del tutor:");

                        txtPhoneNumber.setForeground(new Color(153, 153, 153));
                        txtPhoneNumber.setText("Ingresa el numero de telefono del tutor:");

                        txtEmail.setForeground(new Color(153, 153, 153));
                        txtEmail.setText("Ingresa el correo electronico del tutor:");
                        
                        txtEmergencyContact.setForeground(new Color(153, 153, 153));
                        txtEmergencyContact.setText("Ingresa el nombre del contacto de emergencia:");

                        txtEmergencyPhoneNumber.setForeground(new Color(153, 153, 153));
                        txtEmergencyPhoneNumber.setText("Ingresa el telefono del contacto de emergencia:");

                        txtStreet.setForeground(new Color(153, 153, 153));
                        txtStreet.setText("Ingresa el domicilio del alumno:");

                        txtNo.setForeground(new Color(153, 153, 153));
                        txtNo.setText("Num.Ext");

                        txtApt.setForeground(new Color(153, 153, 153));
                        txtApt.setText("Num.Int");
                           
                        txtDistrict.setForeground(new Color(153, 153, 153));
                        txtDistrict.setText("Ingrese la colonia:");

                        txtCity.setForeground(new Color(153, 153, 153));
                        txtCity.setText("Ingrese la ciudad:");

                    } catch (Exception e){
                        JOptionPane.showMessageDialog(this, "ERROR: VERIFIQUE LOS DATOS INGRESADOS", "ERROR", JOptionPane.ERROR_MESSAGE);
                        System.out.println(e.getMessage());
                    }
                        // la variable edad contiene el valor entero de la cadena
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "EDAD INVALIDA", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }
       
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void txtNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMousePressed
        if (txtName.getText().equals("Ingresa el nombre del alumno:")){
            txtName.setText("");
            txtName.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNameMousePressed

    private void txtNoControlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNoControlMousePressed
        if (txtNoControl.getText().equals("Ingresa el numero de control del alumno:")){
            txtNoControl.setText("");
            txtNoControl.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNoControlMousePressed

    private void txtAgeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgeMousePressed
        if (txtAge.getText().equals("Ingresa la edad del alumno:")){
            txtAge.setText("");
            txtAge.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtAgeMousePressed

    private void txtTypeBloodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTypeBloodMousePressed
        if (txtTypeBlood.getText().equals("Ingresa el tipo de sangre del alumno:")){
            txtTypeBlood.setText("");
            txtTypeBlood.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTypeBloodMousePressed

    private void txtGradeLevelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGradeLevelMousePressed
        if (txtGradeLevel.getText().equals("Ingresa el grado escolar del alumno:")){
            txtGradeLevel.setText("");
            txtGradeLevel.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtGradeLevelMousePressed

    private void txtTutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTutorMousePressed
        if (txtTutor.getText().equals("Ingresa el nombre del tutor:")){
            txtTutor.setText("");
            txtTutor.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTutorMousePressed

    private void txtPhoneNumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhoneNumberMousePressed
        if (txtPhoneNumber.getText().equals("Ingresa el numero de telefono del tutor:")){
            txtPhoneNumber.setText("");
            txtPhoneNumber.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPhoneNumberMousePressed

    private void txtEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMousePressed
        if (txtEmail.getText().equals("Ingresa el correo electronico del tutor:")){
            txtEmail.setText("");
            txtEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtEmailMousePressed

    private void txtEmergencyContactMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmergencyContactMousePressed
        if (txtEmergencyContact.getText().equals("Ingresa el nombre del contacto de emergencia:")){
            txtEmergencyContact.setText("");
            txtEmergencyContact.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtEmergencyContactMousePressed

    private void txtEmergencyPhoneNumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmergencyPhoneNumberMousePressed
        if (txtEmergencyPhoneNumber.getText().equals("Ingresa el telefono del contacto de emergencia:")){
            txtEmergencyPhoneNumber.setText("");
            txtEmergencyPhoneNumber.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtEmergencyPhoneNumberMousePressed

    private void txtStreetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStreetMousePressed
        if (txtStreet.getText().equals("Ingresa el domicilio del alumno:")){
            txtStreet.setText("");
            txtStreet.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtStreetMousePressed

    private void txtNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNoMousePressed
        if (txtNo.getText().equals("Num.Ext")){
            txtNo.setText("");
            txtNo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNoMousePressed

    private void txtAptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAptMousePressed
        if (txtApt.getText().equals("Num.Int")){
            txtApt.setText("");
            txtApt.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtAptMousePressed

    private void txtDistrictMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDistrictMousePressed
        if (txtDistrict.getText().equals("Ingrese la colonia:")){
            txtDistrict.setText("");
            txtDistrict.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtDistrictMousePressed

    private void txtCityMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCityMousePressed
        if (txtCity.getText().equals("Ingrese la ciudad:")){
            txtCity.setText("");
            txtCity.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCityMousePressed

    private void txtAllergyDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergyDescriptionActionPerformed

    }//GEN-LAST:event_txtAllergyDescriptionActionPerformed

    private void rbtnTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTrueActionPerformed
        txtAllergyDescription.setEnabled(true);
    }//GEN-LAST:event_rbtnTrueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.ButtonGroup buttons;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtnFalse;
    private javax.swing.JRadioButton rbtnTrue;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAllergyDescription;
    private javax.swing.JTextField txtApt;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDistrict;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmergencyContact;
    private javax.swing.JTextField txtEmergencyPhoneNumber;
    private javax.swing.JTextField txtGradeLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtNoControl;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtTutor;
    private javax.swing.JTextField txtTypeBlood;
    // End of variables declaration//GEN-END:variables
}
